# Generated by Django 5.2.3 on 2025-06-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosp_tbl',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
