# Generated by Django 5.2.3 on 2025-06-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0002_alter_hosp_tbl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_img', models.FileField(upload_to='pictures')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp_tbl')),
            ],
        ),
    ]
