# Generated by Django 5.2.3 on 2025-06-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0003_doc_tbl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hosp_tbl',
            new_name='dept_tbl',
        ),
    ]
