# Generated by Django 5.2.3 on 2025-06-25 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0005_reg_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_appt_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('test', models.CharField(max_length=40)),
                ('doc_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.reg_tbl')),
            ],
        ),
    ]
